#!/bin/bash

while true; do

#get timestamp
timestamp=$(date '+%Y-%m-%d')

		if [ ! -f "~/downloads/log/rclone/rclone_$timestamp'_'info_share.log" ]; then touch ~/downloads/log/rclone/rclone_$timestamp'_'info_share.log; fi
        rclone move ~/downloads/share gd:/seedhost/completed/share --progress --delete-after --drive-chunk-size 128M --buffer-size 256M --transfers 8 --log-level INFO --log-file ~/downloads/log/rclone/rclone_$timestamp'_'info_share.log >> ~/downloads/log/rclone/rclone_$timestamp'_'progress_share.log
        find ~/downloads/share/* -type d -empty -delete
        sleep 60
done
